### ISSUE TITLE
Official-ish way to check latest SDK version

### ISSUE THREAD

**Issue by hello-josh** [prmtl/appfy.recipe.gae#20]
I ran across this a project on Github today that uses the https://appengine.google.com/api/updatecheck URL to determine the latest app engine sdk for download. I believe this is the same mechanism that the updater uses.

The URL returns

```
release: "1.9.18"
timestamp: 1422656281
api_versions: ['1']
supported_api_versions:
  python:
    api_versions: ['1']
  python27:
    api_versions: ['1']
  go:
    api_versions: ['go1']
  java7:
    api_versions: ['1.0']
```

It might be worth using this method going forward with your 1.9.11 release

https://github.com/rbanffy/appengine-fixture-loader/blob/master/resources/get_current_sdk_version.sh#L3
